apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "querent.fullname" . }}
  labels:
    {{- include "querent.labels" . | nindent 4 }}
data:
  node.yaml: |-
    # ============================ Node Configuration ==============================
    # Website: https://querent.xyz
    # Docs: https://querent.xyz/docs
    # -------------------------------- General settings --------------------------------
    version: {{ .Values.node_config.version }}
    cluster_id: {{ .Values.node_config.cluster_id }}
    node_id: {{ .Values.node_config.node_id }}
    listen_address: {{ .Values.node_config.listen_address }}
    advertise_address: {{ .Values.node_config.advertise_address }}
    gossip_listen_port: {{ .Values.node_config.gossip_listen_port }}
    grpc_listen_port: {{ .Values.node_config.grpc_listen_port }}
    cpu_capacity: {{ .Values.node_config.cpu_capacity }}
    peer_seeds:  {{- if .Values.node_config.peer_seeds }} {{ .Values.node_config.peer_seeds | toYaml | nindent 6 }} {{- else }} [] {{- end }} 
    rest_config:
      listen_port: {{ .Values.node_config.rest_config.listen_port }}
      cors_allow_origins:
        {{- toYaml .Values.node_config.rest_config.cors_allow_origins | nindent 8 }}
      extra_headers:
        {{- toYaml .Values.node_config.rest_config.extra_headers | nindent 8 }}
    storage_configs:
      {{ if .Values.node_config.storage_configs }}
      {{ .Values.node_config.storage_configs | toYaml | nindent 6 }}
      {{- else }}
      []
      {{- end }}
    tracing:
      jaeger:
        enable_endpoint: {{ .Values.node_config.tracing.jaeger.enable_endpoint }}
        lookback_period_hours: {{ .Values.node_config.tracing.jaeger.lookback_period_hours }}
        max_trace_duration_secs: {{ .Values.node_config.tracing.jaeger.max_trace_duration_secs }}
        max_fetch_spans: {{ .Values.node_config.tracing.jaeger.max_fetch_spans }}
