apiVersion: v1
kind: Secret
metadata:
  name: {{ include "querent.fullname" . }}
  labels:
    {{- include "querent.labels" . | nindent 4 }}
type: Opaque
data:
{{- if .Values.node_config.storage_configs.postgres }}
  postgres.yaml: {{ .Values.node_config.storage_configs.postgres.config | b64enc | nindent 2 }}
{{- end }}
{{- if .Values.node_config.storage_configs.milvus }}
  milvus.yaml: {{ .Values.node_config.storage_configs.milvus.config | b64enc | nindent 2 }}
{{- end }}
{{- if .Values.node_config.storage_configs.neo4j }}
  neo4j.yaml: {{ .Values.node_config.storage_configs.neo4j.config | b64enc | nindent 2 }}
{{- end }}
