apiVersion: v1
kind: Secret
metadata:
  name: {{ include "querent.fullname" . }}
  labels:
    {{- include "querent.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.node_config.storage_configs }}
  storage_configs: {{ .Values.node_config.storage_configs | b64enc | nindent 4 }}
  {{- end }}
