apiVersion: v1
kind: Secret
metadata:
  name: {{ include "querent.fullname" . }}
  labels:
    {{- include "querent.labels" . | nindent 4 }}
type: Opaque
data:
{{- if .Values.node_config.storage_configs.postgres }}
  postgres.config.url: {{ required "A valid postgres url must be provided" .Values.node_config.storage_configs.postgres.url | b64enc | quote }}
{{- end }}
{{- if .Values.node_config.storage_configs.milvus }}
  milvus.config.password: {{ required "A valid milvus password must be provided" .Values.node_config.storage_configs.milvus.password | b64enc | quote }}
{{- end }}
{{- if .Values.node_config.storage_configs.neo4j }}
  neo4j.config.password: {{ required "A valid neo4j password must be provided" .Values.node_config.storage_configs.neo4j.password | b64enc | quote }}
{{- end }}
{{- if .Values.node_config.storage_configs.mysql }}
  mysql.config.password: {{ required "A valid mysql password must be provided" .Values.node_config.storage_configs.mysql.password | b64enc | quote }}
{{- end }}
{{- if .Values.node_config.storage_configs.clickhouse }}
  clickhouse.config.password: {{ required "A valid clickhouse password must be provided" .Values.node_config.storage_configs.clickhouse.password | b64enc | quote }}
{{- end }}
{{- if .Values.node_config.storage_configs.elasticsearch }}
  elasticsearch.config.password: {{ required "A valid elasticsearch password must be provided" .Values.node_config.storage_configs.elasticsearch.password | b64enc | quote }}
{{- end }}
{{- if .Values.node_config.storage_configs.redis }}
  redis.config.password: {{ required "A valid redis password must be provided" .Values.node_config.storage_configs.redis.password | b64enc | quote }}
{{- end }}
{{- if .Values.node_config.storage_configs.kafka }}
  kafka.config.password: {{ required "A valid kafka password must be provided" .Values.node_config.storage_configs.kafka.password | b64enc | quote }}
{{- end }}
{{- if .Values.node_config.storage_configs.rabbitmq }}
  rabbitmq.config.password: {{ required "A valid rabbitmq password must be provided" .Values.node_config.storage_configs.rabbitmq.password | b64enc | quote }}
{{- end }}
{{- if .Values.node_config.storage_configs.minio }}
  minio.config.accessKey: {{ required "A valid minio accessKey must be provided" .Values.node_config.storage_configs.minio.accessKey | b64enc | quote }}
  minio.config.secretKey: {{ required "A valid minio secretKey must be provided" .Values.node_config.storage_configs.minio.secretKey | b64enc | quote }}
{{- end }}
{{- if .Values.node_config.storage_configs.s3 }}
  s3.config.accessKey: {{ required "A valid s3 accessKey must be provided" .Values.node_config.storage_configs.s3.accessKey | b64enc | quote }}
  s3.config.secretKey: {{ required "A valid s3 secretKey must be provided" .Values.node_config.storage_configs.s3.secretKey | b64enc | quote }}
{{- end }}
