apiVersion: v1
kind: Secret
metadata:
  name: {{ include "querent.fullname" . }}
  labels:
    {{- include "querent.labels" . | nindent 4 }}
type: Opaque
data:
{{- if .Values.node_config.storage_configs.postgres }}
  postgres.url: {{ .Values.node_config.storage_configs.postgres.config.url | b64enc | nindent 2 }}
{{- end }}
{{- if .Values.node_config.storage_configs.milvus }}
  milvus.password: {{ .Values.node_config.storage_configs.milvus.config.password | b64enc | nindent 2 }}
{{- end }}
{{- if .Values.node_config.storage_configs.neo4j }}
  neo4j.password: {{ .Values.node_config.storage_configs.neo4j.config.password | b64enc | nindent 2 }}
{{- end }}
