{{- if .Values.semanticService.podDisruptionBudget -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "querent.fullname" . }}-semanticService
  labels:
    {{- include "querent.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "querent.semanticService.selectorLabels" . | nindent 6 }}
  {{- toYaml .Values.semanticService.podDisruptionBudget | nindent 2 }}
{{- end -}}