{{- if .Values.semantics.podDisruptionBudget -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "querent.fullname" . }}-semantics
  labels:
    {{- include "querent.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "querent.semantics.selectorLabels" . | nindent 6 }}
  {{- toYaml .Values.semantics.podDisruptionBudget | nindent 2 }}
{{- end -}}