apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "querent.fullname" . }}-semantic-service
  labels:
    {{- include "querent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.semantic-service.replicaCount }}
  serviceName: {{ include "querent.fullname" . }}-headless
  {{- if .Values.searcher.podManagementPolicy }}
  podManagementPolicy: {{ .Values.semantic-service.podManagementPolicy }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "querent.semantic-service.selectorLabels" . | nindent 6 }}
  updateStrategy:
    {{- toYaml .Values.semantic-service.updateStrategy | nindent 4 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "querent.semantic-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "querent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- include "querent.environment" . | nindent 12 }}
            {{- range $key, $value := .Values.semantic-service.extraEnv }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
            {{- end }}
          ports:
            {{- include "querent.ports" . | nindent 12 }}
          startupProbe:
            {{- toYaml .Values.semantic-service.startupProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.semantic-service.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.semantic-service.readinessProbe | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /querent/node.yaml
              subPath: node.yaml
            - name: data
              mountPath: /querent/quester_data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ template "querent.fullname" . }}
            items:
              - key: node.yaml
                path: node.yaml
        {{- if ne .Values.semantic-service.persistentVolume.enabled true }}
        - name: data
          emptyDir: {}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.semantic-service.persistentVolume.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "{{ .Values.semantic-service.persistentVolume.storage }}"
      {{- if .Values.semantic-service.persistentVolume.storageClass }}
        storageClassName: "{{ .Values.semantic-service.persistentVolume.storageClass }}"
      {{- end }}
  {{- end }}