{{- if and ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" ) .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "querent.fullname" . }}
  labels:
    {{- include "querent.labels" . | nindent 4 }}
spec:
  endpoints:
    - path: /metrics
      port: rest 
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      metricRelabelings:
        {{- toYaml .Values.serviceMonitor.metricRelabelings | nindent 8 }}
      relabelings:
        {{- toYaml .Values.serviceMonitor.relabelings | nindent 8 }}
  jobLabel: app.kubernetes.io/instance
  selector:
    matchLabels:
      {{- include "querent.selectorLabels" . | nindent 6 }}
{{- end }}
