apiVersion: v1
kind: Service
metadata:
  name: {{ include "querent.fullname" . }}-semantics
  labels:
    {{- include "querent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 1111
      targetPort: rest
      protocol: TCP
      name: rest
    - port: 3333
      targetPort: grpc
      name: grpc
  selector:
    {{- include "querent.selectorLabels" . | nindent 4 }}
